# Build Specifications for AWS CodeBuild - https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html
# Environment Variables to be configured in CodeBuild Project
# - $AWS_DEFAULT_REGION: Region code, e.g. ap-southeast-1
# - $AWS_ACCOUNT_ID: 12-digit account ID
# - $IMAGE_REPO: ECR registry name
# - $IMAGE_TAG: Usually a version number or "latest"

version: 0.2

phases:
  install:
    commands:
      - yum update -y
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Scanning with Hadolint
      - docker run --rm -i hadolint/hadolint < Dockerfile
      - echo Build started on `date`
      - echo Building the Docker image
      - docker build -t $IMAGE_REPO:$IMAGE_TAG .
      - docker tag $IMAGE_REPO:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO:$IMAGE_TAG
