apiVersion: v1
kind: Service
metadata:
  name: sample-express-api-service
spec:
  selector:
    app: sample-express-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-express-api
  labels:
    app: sample-express-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-express-api
  template:
    metadata:
      labels:
        app: sample-express-api
    spec:
      serviceAccountName: sample-express-api-service
      containers:
        - name: sample-express-api
          image: [URL]
          ports:
            - containerPort: 8000
