apiVersion: v1
kind: Service
metadata:
  name: sample-express-api-service
spec:
  selector:
    app: sample-express-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
