apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: sample-express-api-service
  namespace: sampleexpressapi
spec:
  podSelector:
    matchLabels:
      app: sample-express-api
  listeners:
    - portMapping:
        port: 8000
        protocol: http
  serviceDiscovery:
    dns:
      hostname: sample-express-api-service.sampleexpressapi.svc.cluster.local